90311_Rahalevich/Areas/ApiDemo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _90311_Rahalevich.Areas.ApiDemo.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

90311_Rahalevich/Controllers/InsulinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using _90311_Rahalevich.DAL.Data;
using _90311_Rahalevich.DAL.Entities;

namespace _90311_Rahalevich.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InsulinsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public InsulinsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Insulins
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Insulin>>> GetInsulins(int?
group)
        {
            return await _context
            .Insulins
            .Where(d => !group.HasValue
            || d.InsulinGroupId.Equals(group.Value))
            ?.ToListAsync();
        }
        
        
        
        // GET: api/Insulins/5
                [HttpGet("{id}")]
        public async Task<ActionResult<Insulin>> GetInsulin(int id)
        {
            var insulin = await _context.Insulins.FindAsync(id);

            if (insulin == null)
            {
                return NotFound();
            }

            return insulin;
        }

        // PUT: api/Insulins/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutInsulin(int id, Insulin insulin)
        {
            if (id != insulin.InsulinId)
            {
                return BadRequest();
            }

            _context.Entry(insulin).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!InsulinExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Insulins
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Insulin>> PostInsulin(Insulin insulin)
        {
            _context.Insulins.Add(insulin);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetInsulin", new { id = insulin.InsulinId }, insulin);
        }

        // DELETE: api/Insulins/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Insulin>> DeleteInsulin(int id)
        {
            var insulin = await _context.Insulins.FindAsync(id);
            if (insulin == null)
            {
                return NotFound();
            }

            _context.Insulins.Remove(insulin);
            await _context.SaveChangesAsync();

            return insulin;
        }

        private bool InsulinExists(int id)
        {
            return _context.Insulins.Any(e => e.InsulinId == id);
        }
    }
}

90311_Rahalevich/Areas/ApiDemo/Pages/Index.cshtml
@page
@model _90311_Rahalevich.Areas.ApiDemo.Pages.IndexModel
@{
}
<table class="table table-striped table-sm" id="list">
</table>
<div class="lead" id="info"></div>

@section Scripts
    {
    <script>
    var url = "@Url.Action("GetInsulins", "Insulins")";
    $(document).ready(function () {
        // послать запрос
        $.getJSON(url, function (data) {
            // найти таблицу по id
            var table = $("#list");
            // сформировать строку для каждого полученного объекта
            $.each(data, function (num, value) {
                createRow(num + 1, value).appendTo(table);
            })
        });
    })
            // Функция формирования одной строки таблицы
            // index - порядковый номер
            // data - объект данных
            function createRow(index, data) {
                // создать строку таблицы
                var row = $("<tr>");
                // добавть колонку с порядковым номером
                row.append("<td>" + index + "</td>");
                // добавить колонку с названием
                row.append("<td>" + data.insulinName + "</td>");
                // создать кнопку
                var button = $("<button>")
                    .addClass("btn btn-success") // стиль кнопки
                    .click(data.insulinId, showDetails) // подписка на событие click
                    .text("Подробно"); // надпись
                // создать колонку с кнопкой
                var td = $("<td>").append(button);
                // добавить в строку таблицы
                row.append(td);
                return row;
            }
            //Функция выода информации о выбранном объекте
            function showDetails(e) {
                // Послать запрос
                $.getJSON(url + "/" + e.data, function (data) {
                    // строка информации об объекте
                    var details = data.insulinName + ". Производитель:  "
                        + data.publisher + ". " +
                    "Рейтинг: " + data.rating;
                    $("#info") // Найти блок для информации
                        .empty() // очистить содержимое
                        .text(details); // записать новый текст
                })
            }
    </script>
}